[package]
name = "tweetust"
version = "0.0.1"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "Experimental Twitter Library"
repository = "https://github.com/azyobuzin/tweetust"
keywords = ["twitter", "tweet"]
license = "MIT"

[dependencies]
hyper = "*"
oauthcli = "*"
rustc-serialize = "*"
url = "*"
