[package]
name = "tweetust"
version = "0.2.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "The Twitter API wrapper"
documentation = "https://docs.rs/tweetust/0.2.0/tweetust/"
repository = "https://github.com/azyobuzin/tweetust"
keywords = ["twitter", "tweet"]
license = "MIT"
exclude = ["clientgen/**/*", ".*"]
build = "build.rs"

[dependencies]
hyper = "0.9"
oauthcli = { version = "1.0.1", features = ["hyper"] }
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
url = "1.2"

[build-dependencies]
serde_codegen = "0.8.10"
