[package]
name = "tweetust"
version = "0.1.1"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "Experimental Twitter Library"
documentation = "http://azyobuzin.github.io/tweetust/tweetust/"
repository = "https://github.com/azyobuzin/tweetust"
keywords = ["twitter", "tweet"]
license = "MIT"
exclude = ["clientgen/**/*", ".*"]

[dependencies]
hyper = "0.9"
oauthcli = "0.1"
rustc-serialize = "0.3"
url = "1.2"
