[package]
name = "tweetust"
version = "0.1.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "Experimental Twitter Library"
documentation = "http://azyobuzin.github.io/tweetust/tweetust/"
repository = "https://github.com/azyobuzin/tweetust"
keywords = ["twitter", "tweet"]
license = "MIT"
exclude = ["clientgen/**/*", ".*"]

[dependencies]
hyper = "*"
oauthcli = "*"
rustc-serialize = "*"
url = "*"
