[package]
name = "clientgen_test"
version = "0.1.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
publish = false

[dependencies]
Inflector = { version = "0.10", default-features = false }
log = "0.3"
matches = "0.1"
nom = "1.2"
